### ISSUE TITLE
Loading delay issue

### ISSUE THREAD

**Issue by gitrummy** [bramkragten/swipe-card#12]
Hi there.

I'm running the latest Home Assistant core and am getting a significant loading delay on all cards that use swiper. The example GIF below shows my A/C card loading a few seconds after everything else. Any help would be greatly appreciated. 
![GIF-200331_115105](https://user-images.githubusercontent.com/11849147/77969426-3312da80-7346-11ea-9083-7b09f324b3fb.gif)

**Comment by guillpocovi** [comment]
Hi,

Same here. In my understanding, this is due to the following change: https://developers.home-assistant.io/blog/2020/02/18/106-custom-card-changes/#helper-functions

**Comment by Shamshala** [comment]
Same for me.

**Comment by TheBToby** [comment]
Same here. I use decluttering-cards inside the swipe-card. The delays are painfully long. Would definitely appreciate if you could have a look on this

**Comment by darynwilkinson** [comment]
Also experiencing this issue.

**Comment by askusbloodfist** [comment]
Same. update plz.

**Comment by RomRider** [comment]
This should be fixed with the latest update and the PR I did here #14. It was related to the card updating itself too much.

**Comment by darynwilkinson** [comment]
Looks like that fixed it. Thank you.

**Comment by TheBToby** [comment]
Beautiful. Works for me. Thanks!!

**Comment by smartqasa** [comment]
Same here. Sometimes 10 seconds.
