### ISSUE TITLE
During swipe, entity triggers on phone and tablet only.

### ISSUE THREAD

**Issue by syedkami** [bramkragten/swipe-card#15]
Hi, first I appreciate, this component is gr8 in HA.
I have little issue, when I use type buttons for entities, and I have multiple button to swipe, then on sliding or swiping, entity triggers. I just want to swipe not click or trigger. And it just happen in mobile and tablet, not in browser. I am using android phone and tablet.

Kindly look into this.
 Thanks

**Comment by bramkragten** [comment]
What device is this? Works fine in Chrome on Android

**Comment by syedkami** [comment]
Hi. Thanks. Now in last update, its working fine. 
In previous version, on android fone and tablet, when I swipe, then entity triggers. Suppose, if there are button cards for swipe, then each entity switch on or off. But in this update is ok. Thanks.

Want to ask onething, is it possible to swipe navigation cards? Suppose, there are four cards Home, bedroom, kitchen and lounch. Swiping all as cards, when i click on any card, then goes to kitchen navigation page, or home navigation page entities?

**Comment by bramkragten** [comment]
Sure, that's just the `tap_action` of the button <https://www.home-assistant.io/lovelace/actions/#navigation_path>
