### ISSUE TITLE
help me for swipe-card option

### ISSUE THREAD

**Issue by Subia75** [bramkragten/swipe-card#54]
The swiper options were at this link (http://idangero.us/swiper/api/).
But now the link doesn't work anymore.
I ask if there is another place where I can find the parameters to be included in my lovelage cards.

thank you

**Comment by ildar170975** [comment]
![image](https://user-images.githubusercontent.com/71872483/182639727-4d57102f-390a-4063-9bff-598b15dfcc3e.png)

**Comment by Subia75** [comment]
Thank you,
I thought it was one of those disabled web pages and didn't try to click on the banners above.

I close
