### ISSUE TITLE
Binary Sensor state is On/Off instead of Open/Closed

### ISSUE THREAD

**Issue by sheminasalam** [bramkragten/swipe-card#73]
After the latest update the binary sensor of type door is showing on/off state than open/closed. 
![image](https://user-images.githubusercontent.com/45196177/232234368-c916dbc8-0db7-464e-9452-adf2da22a8c8.png)

**Comment by ildar170975** [comment]
You have not posted any code for this issue.
People have to guess what could cause your issue.
Probably a card you are using inside `swipe-card` causes the issue - then you should ask in a corresponding repo.
