### ISSUE TITLE
Is this repo dead and will never be developed again?

### ISSUE THREAD

**Issue by alexsaas** [bramkragten/swipe-card#86]
@bramkragten can you please tell us if your repo is dead and will never be developed again?

**Comment by bramkragten** [comment]
No, not dead. Will update soon.

**Comment by alexsaas** [comment]
Great to hear. Thank you very much! I'm looking forward to it. 🙏

**Comment by RobertoCravallo** [comment]
+1

**Comment by Zuendapp** [comment]
Hi @bramkragten

can you give us a approximately date?
 
 Thank you!

**Comment by chintito4ever** [comment]
Almost after a year, still no updates.
